spring:
  application:
    name: users

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${spring.application.name}:${server.port}

server:
  port: 8981
